### ISSUE TITLE
Build on maia (CentOS6.5) fails. setfill and setw are not declared in scope.

### ISSUE THREAD

**Issue by tph-thuering** [SwissTPH/openmalaria#130]
/home/medizin/thuerint/openmalaria/model/util/misc.cpp: In function ‘void OM::UnitParse::formatDate(std::ostream&, OM::SimTime)’:
/home/medizin/thuerint/openmalaria/model/util/misc.cpp:221: error: ‘setfill’ was not declared in this scope
/home/medizin/thuerint/openmalaria/model/util/misc.cpp:221: error: ‘setw’ was not declared in this scope

**Comment by tph-thuering** [comment]
Done
